@startgantt
Project starts 2023-03-10

[Definición del alcance del sistema] lasts 1 day
[Definición del alcance del sistema] starts 2023-03-10
[Definición del alcance del sistema] ends 2023-03-10

[Análisis de los requisitos] lasts 3 days
[Análisis de los requisitos] starts 2023-03-10
[Análisis de los requisitos] ends 2023-03-12

[Análisis de los casos de uso] lasts 3 days
[Análisis de los casos de uso] starts 2023-03-12
[Análisis de los casos de uso] ends 2023-03-14

[Análisis de clases] lasts 2 days
[Análisis de clases] starts 2023-03-15
[Análisis de clases] ends 2023-03-16

[Diseño de los prototipos de las interfaces de usuario] lasts 1 day
[Diseño de los prototipos de las interfaces de usuario] starts 2023-03-16
[Diseño de los prototipos de las interfaces de usuario] ends 2023-03-16

[Elaboración del plan de pruebas] lasts 2 days
[Elaboración del plan de pruebas] starts 2023-03-16
[Elaboración del plan de pruebas] ends 2023-03-17

@endgantt
