@startgantt
Project starts 2023-10-17
saturday are closed
sunday are closed

[Implementación del subsistema de gestión de reservas] starts 2023-10-17
[Implementación del subsistema de gestión de reservas] ends 2023-12-28



@endgantt
