@startgantt
Project starts 2024-05-31

[Elaboración de la planificación final] starts 2024-05-31
[Elaboración de la planificación final] ends 2024-05-31

[Cálculo del presupuesto final] starts 2024-06-03
[Cálculo del presupuesto final] ends 2024-06-03

[Reunión de cierre del proyecto] starts 2024-06-03
[Reunión de cierre del proyecto] ends 2024-06-03

@endgantt