@startgantt
Project starts 2023-08-25
saturday are closed
sunday are closed

[Implementación del subsistema de gestión de actividades] starts 2023-08-25
[Implementación del subsistema de gestión de actividades] ends 2023-10-16


@endgantt
